{{- $ingress := .Values.ingress -}}
{{- if $ingress.enabled -}}
{{- $apiVersion := "networking.k8s.io/v1" -}}
apiVersion: {{ template "xetusoss-archiva.ingressApiVersion" . }}
kind: Ingress
metadata:
  name: {{ template "xetusoss-archiva.fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{- with $ingress.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
  {{- end }}
  labels:
    app: {{ template "xetusoss-archiva.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}  
    {{- with $ingress.labels }}
    {{- range $key, $value := . }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
    {{- end }}  
spec:
{{- if $ingress.ingressClassName }}
  ingressClassName: {{ $ingress.ingressClassName }}
{{- end }}
{{- if $ingress.tls }}
  tls:
    {{- range $ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ tpl . $ | quote }}
      {{- end }}
      {{- with .secretName }}
      secretName: {{ tpl . $ }}
      {{- end }}
    {{- end }}
{{- end }}
  rules:
    {{- $gitversion := .Capabilities.KubeVersion.GitVersion -}}
    {{- range .Values.ingress.rules }}
    - host: {{ tpl .host $ | quote }}
      http:
        paths:
          {{- range .paths }}
          - {{ if semverCompare ">=1.19-0" $gitversion -}}
            path: {{ tpl .path $ | quote }}
            pathType: {{ .pathType }}
            {{- else -}}
            path: {{ tpl .path $ | quote }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $gitversion }}
              service:
                name: {{ template "xetusoss-archiva.fullname" $ }}
                port:
                  name: {{ $ingress.servicePort }}
              {{- else }}
              serviceName: {{ template "xetusoss-archiva.fullname" $ }}
              servicePort: http
              {{- end }}
          {{- end }}
    {{- end }}
{{- end -}}
