{{- if .Values.ingress.enabled -}}
apiVersion: {{ template "xetusoss-archiva.ingressApiVersion" . }}
kind: Ingress
metadata:
  name: {{ template "xetusoss-archiva.fullname" . }}
  labels:
    app: {{ template "xetusoss-archiva.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key | quote }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
  - host: {{ .Values.proxy.hostname }}
    http:
      paths:
        - {{ if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
          path: {{ default "/" .Values.proxy.pathPrefix }}
          pathType: Prefix
          {{- else -}}
          path: {{ default "" .Values.proxy.pathPrefix }}
          {{- end }}
          backend:
            {{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
            service:
              name: {{ include "xetusoss-archiva.fullname" . }}
              port: 
                name: http
            {{- else }}
            serviceName: {{ include "xetusoss-archiva.fullname" . }}
            servicePort: http
            {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - secretName: {{ template "xetusoss-archiva.tlsSecret" . }}
      hosts:
        - {{ .Values.proxy.hostname }}
  {{- end }}
{{- end }}